name: Docker Image CI

on: [push, pull_request]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker compose
      run: docker-compose up -d
    - name: Check running containers
      run: docker ps -a
    - name: Run tests
      run: python manage.py test
