name: Docker Image CI

on: [push, pull_request]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build docker image and start docker compose
      run: docker-compose up --build -d
    - name: Check running containers
      run: docker ps -a
    - name: Run django tests
      run: docker-compose exec -T web python manage.py test
